# Generated by Django 5.2 on 2025-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(db_column='ID_administrador', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(db_column='ID_alerta', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(db_column='ID_avaliacao', primary_key=True, serialize=False)),
                ('nota', models.IntegerField(blank=True, db_column='Nota', null=True)),
            ],
            options={
                'db_table': 'Avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BandeiraCartao',
            fields=[
                ('id_bandeira_cartao', models.AutoField(db_column='ID_bandeira_cartao', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Bandeira_Cartao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartaConducao',
            fields=[
                ('id_carta_conducao', models.AutoField(db_column='ID_carta_conducao', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True, unique=True)),
                ('data_emissao', models.DateField(blank=True, db_column='Data_emissao', null=True)),
                ('data_validade', models.DateField(blank=True, db_column='Data_validade', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('foto', models.CharField(blank=True, db_column='Foto', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Carta_Conducao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cc', models.AutoField(db_column='ID_cc', primary_key=True, serialize=False)),
                ('digito_seguranca', models.IntegerField(blank=True, db_column='Digito_seguranca', null=True)),
                ('data_validade', models.DateField(blank=True, db_column='Data_validade', null=True)),
                ('token', models.CharField(blank=True, db_column='Token', max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'Cartao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartaoUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Cartao_Utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatViagem',
            fields=[
                ('id_chat_viagem', models.AutoField(db_column='ID_chat_viagem', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Chat_Viagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id_condutor', models.AutoField(db_column='ID_condutor', primary_key=True, serialize=False)),
                ('documento_reg_criminal', models.CharField(blank=True, db_column='Documento_reg_criminal', max_length=255, null=True)),
                ('documento_comprov_residencia', models.CharField(blank=True, db_column='Documento_comprov_residencia', max_length=255, null=True)),
                ('reputacao', models.IntegerField(blank=True, db_column='Reputacao', null=True)),
                ('data_criacao', models.DateField(blank=True, db_column='Data_criacao', null=True)),
            ],
            options={
                'db_table': 'Condutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondutorVeiculo',
            fields=[
                ('id_condutor_veiculo', models.AutoField(db_column='ID_condutor_veiculo', primary_key=True, serialize=False)),
                ('documento_arquivo', models.CharField(blank=True, db_column='Documento_arquivo', max_length=255, null=True)),
                ('data_emissao', models.DateField(blank=True, db_column='Data_emissao', null=True)),
                ('data_validade', models.DateField(blank=True, db_column='Data_validade', null=True)),
            ],
            options={
                'db_table': 'Condutor_Veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id_conselho', models.AutoField(db_column='ID_conselho', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Conselho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='ID_contacto', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorVeiculo',
            fields=[
                ('id_cor_veiculo', models.AutoField(db_column='ID_cor_veiculo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Cor_Veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DadosMb',
            fields=[
                ('id_mb', models.AutoField(db_column='ID_mb', primary_key=True, serialize=False)),
                ('referencia', models.IntegerField(blank=True, db_column='Referencia', null=True)),
                ('entidade', models.IntegerField(blank=True, db_column='Entidade', null=True)),
                ('data_limite', models.DateField(blank=True, db_column='Data_limite', null=True)),
            ],
            options={
                'db_table': 'Dados_MB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desvio',
            fields=[
                ('id_desvio', models.AutoField(db_column='ID_desvio', primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(blank=True, db_column='Data_emissao', null=True)),
            ],
            options={
                'db_table': 'Desvio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.AutoField(db_column='ID_distrito', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(db_column='ID_estado_civil', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Estado_Civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Freguesia',
            fields=[
                ('id_freguesia', models.AutoField(db_column='ID_freguesia', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Freguesia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(db_column='ID_grupo', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True)),
                ('data_criacao', models.DateField(blank=True, db_column='Data_criacao', null=True)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaVeiculo',
            fields=[
                ('id_marca_veiculo', models.AutoField(db_column='ID_marca_veiculo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Marca_Veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(db_column='ID_mensagem', primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, db_column='Valor', max_length=2000, null=True)),
                ('data_envio', models.DateField(blank=True, db_column='Data_envio', null=True)),
                ('lida', models.IntegerField(blank=True, db_column='Lida', null=True)),
            ],
            options={
                'db_table': 'Mensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id_modelo_veiculo', models.AutoField(db_column='ID_modelo_veiculo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Modelo_Veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id_morada', models.AutoField(db_column='ID_morada', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Morada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id_nacionalidade', models.AutoField(db_column='ID_nacionalidade', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Nacionalidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_ocorrencia', models.AutoField(db_column='ID_ocorrencia', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=2000, null=True)),
                ('data_envio', models.DateField(blank=True, db_column='Data_envio', null=True)),
                ('data_lida', models.DateField(blank=True, db_column='Data_lida', null=True)),
            ],
            options={
                'db_table': 'Ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(db_column='ID_pagamento', primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, db_column='Valor', null=True)),
                ('data_pagamento', models.DateField(blank=True, db_column='Data_pagamento', null=True)),
            ],
            options={
                'db_table': 'Pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(db_column='ID_pais', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id_passageiro', models.AutoField(db_column='ID_passageiro', primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(blank=True, db_column='Data_criacao', null=True)),
            ],
            options={
                'db_table': 'Passageiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassageiroViagem',
            fields=[
                ('id_passageiro_viagem', models.AutoField(db_column='ID_passageiro_viagem', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Passageiro_Viagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id_ponto', models.AutoField(db_column='ID_ponto', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Ponto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PontoViagem',
            fields=[
                ('id_ponto_viagem', models.AutoField(db_column='ID_ponto_viagem', primary_key=True, serialize=False)),
                ('destino', models.IntegerField(blank=True, db_column='Destino', null=True)),
            ],
            options={
                'db_table': 'Ponto_Viagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(db_column='ID_reserva', primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(blank=True, db_column='Data_emissao', null=True)),
                ('valor', models.IntegerField(blank=True, db_column='Valor', null=True)),
            ],
            options={
                'db_table': 'Reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusDesvio',
            fields=[
                ('id_status_desvio', models.AutoField(db_column='ID_status_desvio', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Status_Desvio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusViagem',
            fields=[
                ('id_status_viagem', models.AutoField(db_column='ID_status_viagem', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Status_Viagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id_suspensao', models.AutoField(db_column='ID_suspensao', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=2000, null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='Data_inicio', null=True)),
                ('data_fim', models.DateField(blank=True, db_column='Data_fim', null=True)),
            ],
            options={
                'db_table': 'Suspensao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAlerta',
            fields=[
                ('id_tipo_alerta', models.AutoField(db_column='ID_tipo_alerta', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tipo_Alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id_tipo_categoria', models.AutoField(db_column='ID_tipo_categoria', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tipo_Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id_tipo_contacto', models.AutoField(db_column='ID_tipo_contacto', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tipo_Contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id_tipo_ocorrencia', models.AutoField(db_column='ID_tipo_ocorrencia', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tipo_Ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id_tipo_pagamento', models.AutoField(db_column='ID_tipo_pagamento', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Tipo_Pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id_tipo_veiculo', models.AutoField(db_column='ID_tipo_veiculo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Tipo_Veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id_utilizador', models.AutoField(db_column='ID_utilizador', primary_key=True, serialize=False)),
                ('nome_primeiro', models.CharField(blank=True, db_column='Nome_Primeiro', max_length=30, null=True)),
                ('nome_ultimo', models.CharField(blank=True, db_column='Nome_Ultimo', max_length=30, null=True)),
                ('data_nasc', models.DateField(blank=True, db_column='Data_nasc', null=True)),
                ('genero', models.CharField(blank=True, db_column='Genero', max_length=1, null=True)),
                ('numero_cc', models.IntegerField(blank=True, db_column='Numero_CC', null=True)),
                ('data_criacao', models.DateField(blank=True, db_column='Data_criacao', null=True)),
                ('senha', models.CharField(blank=True, db_column='Senha', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(db_column='ID_veiculo', primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, db_column='Matricula', max_length=7, null=True, unique=True)),
                ('data_fabricacao', models.DateField(blank=True, db_column='Data_fabricacao', null=True)),
                ('ativo', models.IntegerField(blank=True, db_column='Ativo', null=True)),
            ],
            options={
                'db_table': 'Veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id_viagem', models.AutoField(db_column='ID_viagem', primary_key=True, serialize=False)),
                ('data_viagem', models.DateField(blank=True, db_column='Data_viagem', null=True)),
                ('distancia_percorrida', models.IntegerField(blank=True, db_column='Distancia_percorrida', null=True)),
            ],
            options={
                'db_table': 'Viagem',
                'managed': False,
            },
        ),
    ]
